import './App.css';
import { useRef } from 'react';
import { Workbook } from "@fortune-sheet/react";
import "@fortune-sheet/react/dist/index.css";

function App() {
  const ref = useRef(null);

  const sheetConfig = {
    column: 26,
    row: 50,
    allowEdit: true,
    showToolbar: true,
    showFormulaBar: true,
    showSheetTabs: false,
    addRows:false
  };


  const handleSheetChange = () => {
    if (ref.current) {
      const sheetData = ref.current.getSheet();
      window.currentSheetData = sheetData;
      window.top.postMessage({
        type: "sheetDataUpdated",
        source:"sheetAcees",
        data: sheetData
      }, "*"); 
      localStorage.setItem('sheetData', JSON.stringify(sheetData));
      console.log(sheetData, 'Latest sheet data');
    }
  };

    // Listen for messages from the parent window
    window.addEventListener("message", (event) => {
        // Check the origin of the event for security
        if (event.data.source !== "sheetAcees") {
        return;
        }
    
        // Handle the incoming messages
        const { type } = event.data;
    
        switch (type) {
        case "resetSheet":
            resetSheet();
            break;
        case "updateSheetData":
            updateSheetData();
            break;
        default:
            console.log("Unknown action:", type);
        }
    });

  const resetSheet = () => {
    let updatedJson = {
      "name": "Sheet1",
      "status": 1,
      "celldata":[],
    }
    let currentJson = {
      ...updatedJson,
      sheetConfig
    }

    if(ref.current){
      let currentSheetId = ref.current.getSheet().id;
      currentJson.id = currentSheetId;
      ref.current.updateSheet([currentJson]);
    }
  }

  const updateSheetData = () => {
    updateSheet();
  }

  const updateSheet = () => {
    let updatedJson;
    updatedJson = {
      "name": "Sheet1",
      // "id": "bf2eb9e4-a833-4e03-9da1-74b0b66f2dd4",
      "status": 1,
      "data": [
          [
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null
          ],
          [
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null
          ],
          [
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null
          ],
          [
              null,
              null,
              {
                  "m": "dasd",
                  "ct": {
                      "fa": "General",
                      "t": "g"
                  },
                  "v": "dasd"
              },
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              {
                  "v": "23",
                  "ct": {
                      "fa": "General",
                      "t": "n"
                  },
                  "m": "23"
              },
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null
          ],
          [
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              {
                  "v": "33",
                  "ct": {
                      "fa": "General",
                      "t": "n"
                  },
                  "m": "33"
              },
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null
          ],
          [
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              {
                  "v": "42",
                  "ct": {
                      "fa": "General",
                      "t": "n"
                  },
                  "m": "42"
              },
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null
          ],
          [
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              {
                  "m": "adsda",
                  "ct": {
                      "fa": "General",
                      "t": "g"
                  },
                  "v": "adsda"
              },
              null,
              null,
              null,
              null,
              {
                  "v": "44",
                  "ct": {
                      "fa": "General",
                      "t": "n"
                  },
                  "m": "44"
              },
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null
          ],
          [
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              {
                  "v": "64",
                  "ct": {
                      "fa": "General",
                      "t": "n"
                  },
                  "m": "64"
              },
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null
          ],
          [
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              {
                  "v": 23,
                  "f": "=SUM(m4,m9)",
                  "ct": {
                      "fa": "General",
                      "t": "n"
                  },
                  "m": "23"
              },
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null
          ],
          [
              null,
              null,
              {
                  "m": "addas",
                  "ct": {
                      "fa": "General",
                      "t": "g"
                  },
                  "v": "addas"
              },
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              {
                  "v": 229,
                  "f": "=SUM(m4:m9)",
                  "ct": {
                      "fa": "General",
                      "t": "n"
                  },
                  "m": "229"
              },
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null
          ],
          [
              null,
              null,
              null,
              null,
              null,
              {
                  "m": "dsaasd",
                  "ct": {
                      "fa": "General",
                      "t": "g"
                  },
                  "v": "dsaasd"
              },
              null,
              null,
              {
                  "m": "adasda",
                  "ct": {
                      "fa": "General",
                      "t": "g"
                  },
                  "v": "adasda"
              },
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null
          ],
          [
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null
          ],
          [
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null
          ],
          [
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null
          ],
          [
              null,
              null,
              null,
              {
                  "m": "adada",
                  "ct": {
                      "fa": "General",
                      "t": "g"
                  },
                  "v": "adada"
              },
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null
          ],
          [
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null
          ],
          [
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null
          ],
          [
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              {
                  "m": "addas",
                  "ct": {
                      "fa": "General",
                      "t": "g"
                  },
                  "v": "addas"
              },
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null
          ],
          [
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null
          ],
          [
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null
          ],
          [
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null
          ],
          [
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null
          ],
          [
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null
          ],
          [
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null
          ],
          [
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null
          ],
          [
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null
          ],
          [
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null
          ],
          [
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null
          ],
          [
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null
          ],
          [
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null
          ],
          [
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null
          ],
          [
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null
          ],
          [
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null
          ],
          [
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null
          ],
          [
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null
          ],
          [
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null
          ],
          [
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null
          ],
          [
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null
          ],
          [
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null
          ],
          [
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null
          ],
          [
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null
          ],
          [
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null
          ],
          [
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null
          ],
          [
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null
          ],
          [
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null
          ],
          [
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null
          ],
          [
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null
          ],
          [
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null
          ],
          [
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null
          ],
          [
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null
          ]
      ],
      "calcChain": [
          {
              "r": 8,
              "c": 12,
              "id": "bf2eb9e4-a833-4e03-9da1-74b0b66f2dd4"
          },
          {
              "r": 9,
              "c": 12,
              "id": "bf2eb9e4-a833-4e03-9da1-74b0b66f2dd4"
          }
      ],
      "celldata": [
          {
              "r": 3,
              "c": 2,
              "v": {
                  "m": "dasd",
                  "ct": {
                      "fa": "General",
                      "t": "g"
                  },
                  "v": "dasd"
              }
          },
          {
              "r": 3,
              "c": 12,
              "v": {
                  "v": "23",
                  "ct": {
                      "fa": "General",
                      "t": "n"
                  },
                  "m": "23"
              }
          },
          {
              "r": 4,
              "c": 12,
              "v": {
                  "v": "33",
                  "ct": {
                      "fa": "General",
                      "t": "n"
                  },
                  "m": "33"
              }
          },
          {
              "r": 5,
              "c": 12,
              "v": {
                  "v": "42",
                  "ct": {
                      "fa": "General",
                      "t": "n"
                  },
                  "m": "42"
              }
          },
          {
              "r": 6,
              "c": 7,
              "v": {
                  "m": "adsda",
                  "ct": {
                      "fa": "General",
                      "t": "g"
                  },
                  "v": "adsda"
              }
          },
          {
              "r": 6,
              "c": 12,
              "v": {
                  "v": "44",
                  "ct": {
                      "fa": "General",
                      "t": "n"
                  },
                  "m": "44"
              }
          },
          {
              "r": 7,
              "c": 12,
              "v": {
                  "v": "64",
                  "ct": {
                      "fa": "General",
                      "t": "n"
                  },
                  "m": "64"
              }
          },
          {
              "r": 8,
              "c": 12,
              "v": {
                  "v": 23,
                  "f": "=SUM(m4,m9)",
                  "ct": {
                      "fa": "General",
                      "t": "n"
                  },
                  "m": "23"
              }
          },
          {
              "r": 9,
              "c": 2,
              "v": {
                  "m": "addas",
                  "ct": {
                      "fa": "General",
                      "t": "g"
                  },
                  "v": "addas"
              }
          },
          {
              "r": 9,
              "c": 12,
              "v": {
                  "v": 229,
                  "f": "=SUM(m4:m9)",
                  "ct": {
                      "fa": "General",
                      "t": "n"
                  },
                  "m": "229"
              }
          },
          {
              "r": 10,
              "c": 5,
              "v": {
                  "m": "dsaasd",
                  "ct": {
                      "fa": "General",
                      "t": "g"
                  },
                  "v": "dsaasd"
              }
          },
          {
              "r": 10,
              "c": 8,
              "v": {
                  "m": "adasda",
                  "ct": {
                      "fa": "General",
                      "t": "g"
                  },
                  "v": "adasda"
              }
          },
          {
              "r": 14,
              "c": 3,
              "v": {
                  "m": "adada",
                  "ct": {
                      "fa": "General",
                      "t": "g"
                  },
                  "v": "adada"
              }
          },
          {
              "r": 17,
              "c": 7,
              "v": {
                  "m": "addas",
                  "ct": {
                      "fa": "General",
                      "t": "g"
                  },
                  "v": "addas"
              }
          }
      ]
    }
    if(window.updateSheetData && window.updateSheetData.status){
      updatedJson = window.updateSheetData;
      let currentJson = {
        ...updatedJson,
        sheetConfig
      }
  
      if(ref.current){
        let currentSheetId = ref.current.getSheet().id;
        currentJson.id = currentSheetId;
        ref.current.updateSheet([currentJson]);
      }
    }
  }

  return (
    <>
      <Workbook {...sheetConfig}
        data={[{ name: "Sheet1" }]}
        ref={ref}
        onChange={handleSheetChange}
      />
      <button onClick={updateSheet}>Get Data</button>
    </>
  );
}

export default App;